# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'Testes' do

end

target 'TestesTests' do

	pod ‘Quick’
	pod ’Nimble’

end

target 'TestesUITests' do

end

