xcodeproj 'PocPinterest.xcodeproj/'

# Uncomment this line to define a global platform for your project
platform :tvos, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'PocPinterest' do

    pod 'Alamofire', '~> 3.4'
    pod 'AlamofireImage', '~> 2.0'
    pod 'SwiftyJSON'

end

target 'PocPinterestTests' do

end

target 'PocPinterestUITests' do

end

