# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'CarometroGravatar' do
  pod 'CryptoSwift'
  pod 'MBProgressHUD', '~>0.9.1'
end

target 'CarometroGravatarTests' do

end

